#define RADAR_POS_SELF -1
#define RADAR_POS_CENTER -2
#define RADAR_MAP_TYPE_SAVED 'S'
#define RADAR_MAP_TYPE_SINGLE 'D'
#define RADAR_MAP_TMP -1
#define RADAR_LENTH_TYPE_MAX 'X'
#define RADAR_LENTH_TYPE_MIN 'I'
#define RADAR_LENTH_TYPE_NORMAL 'L'
#define RADAR_LENTH_TYPE_NON 'N'
#define RADAR_LENTH_TYPE_FAR 'F'
#define RADAR_RANGE_MAX  119.9
#define RADAR_RANGE_MIN  -119.6
#define RADAR_TIME  105

#define Degree_range 10
#define WIN_SIZE 800.0

#define LINE_THRESHOLD 0.04363323129 //5degree
#define LINE_THRESHOLD_RANGE 0.34906585038 //40degree
#define LINE_OVER_THRESHOLD 2.79252680321
